# Generated by Django 4.0.5 on 2022-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
